name: Create Package

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.X
      - run: npm install
      - name: Extract SVG-Data
      - run: npm run build
      - name: Setup dotnet
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x
      - name: Build Project
        run: dotnet build -c release MudBlazor.MaterialDesignIcons
      - name: Create Package
        run: dotnet pack -c release MudBlazor.MaterialDesignIcons