name: .NET

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release

env:
  VersionAppendix: -alpha-${{ github.run_number }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
      - name: Install @mdi/svg
        run: npm install
      - name: Get @mdi/svg version
        run: |
          MDI_VERSION=$(node -p "require('./node_modules/@mdi/svg/package.json').version")
          echo "MDI_VERSION=$MDI_VERSION" >> $GITHUB_ENV
      - name: Set pre-release version
        run: echo "PACKAGE_VERSION=${{ env.MDI_VERSION }}-alpha-${{ github.run_number }}" >> $GITHUB_ENV
        if: github.base_ref  == 'main'
      - name: Set release version
        run: echo "PACKAGE_VERSION=${{ env.MDI_VERSION }}.${{ github.run_number }}" >> $GITHUB_ENV
        if: github.base_ref  == 'release'
      - name: Extract svg data
        run: npm run build
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release -p:Version=${{ env.PACKAGE_VERSION }}
      - name: Pack
        run: dotnet pack -c Release -p:Version=${{ env.PACKAGE_VERSION }}
      - name: Push to nuget 
        run: dotnet nuget push Bromix.MudBlazor.MaterialDesignIcons/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      # - name: Provide download
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: nugetpackage
      #     path: '**/*.nupkg'
